name: CI - Lint e Tipagem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validacao:
    name: Validação de Código
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: npm install

      - name: Verificar erros de formatação (Lint)
        run: npm run lint

      - name: Verificar erros de tipagem (TypeScript)
        run: npx tsc --noEmit
